/**
 */
package com.github.icelyframework.service;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getName <em>Name</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isAbstract <em>Abstract</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isAggregateRoot <em>Aggregate Root</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getRelations <em>Relations</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getInheritance <em>Inheritance</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getRepository <em>Repository</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getOperations <em>Operations</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getAggregate <em>Aggregate</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getPackage <em>Package</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isGapClass <em>Gap Class</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isCache <em>Cache</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isOptimisticLocking <em>Optimistic Locking</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getDatabaseTable <em>Database Table</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getValidate <em>Validate</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#getDiscriminatorColumnValue <em>Discriminator Column Value</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isScaffold <em>Scaffold</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isGeneratedByJHipster <em>Generated By JHipster</em>}</li>
 *   <li>{@link com.github.icelyframework.service.DomainObject#isGeneratedBySculptor <em>Generated By Sculptor</em>}</li>
 * </ul>
 *
 * @see com.github.icelyframework.service.ServicePackage#getDomainObject()
 * @model abstract="true"
 * @generated
 */
public interface DomainObject extends SimpleType {
	/**
	 * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
	 * The list contents are of type {@link com.github.icelyframework.service.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Properties</em>' containment reference list.
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Properties()
	 * @model containment="true"
	 * @generated
	 */
	EList<Property> getProperties();

	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Abstract</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Abstract</em>' attribute.
	 * @see #setAbstract(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Abstract()
	 * @model
	 * @generated
	 */
	boolean isAbstract();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isAbstract <em>Abstract</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Abstract</em>' attribute.
	 * @see #isAbstract()
	 * @generated
	 */
	void setAbstract(boolean value);

	/**
	 * Returns the value of the '<em><b>Aggregate Root</b></em>' attribute.
	 * The default value is <code>"true"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Aggregate Root</em>' attribute.
	 * @see #setAggregateRoot(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_AggregateRoot()
	 * @model default="true" unique="false"
	 * @generated
	 */
	boolean isAggregateRoot();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isAggregateRoot <em>Aggregate Root</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Aggregate Root</em>' attribute.
	 * @see #isAggregateRoot()
	 * @generated
	 */
	void setAggregateRoot(boolean value);

	/**
	 * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
	 * The list contents are of type {@link com.github.icelyframework.service.Relation}.
	 * It is bidirectional and its opposite is '{@link com.github.icelyframework.service.Relation#getSource <em>Source</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Relations</em>' containment reference list.
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Relations()
	 * @see com.github.icelyframework.service.Relation#getSource
	 * @model opposite="source" containment="true"
	 * @generated
	 */
	EList<Relation> getRelations();

	/**
	 * Returns the value of the '<em><b>Inheritance</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Inheritance</em>' containment reference.
	 * @see #setInheritance(Inheritance)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Inheritance()
	 * @model containment="true"
	 * @generated
	 */
	Inheritance getInheritance();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getInheritance <em>Inheritance</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Inheritance</em>' containment reference.
	 * @see #getInheritance()
	 * @generated
	 */
	void setInheritance(Inheritance value);

	/**
	 * Returns the value of the '<em><b>Repository</b></em>' containment reference.
	 * It is bidirectional and its opposite is '{@link com.github.icelyframework.service.Repository#getAggregateRoot <em>Aggregate Root</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Repository</em>' containment reference.
	 * @see #setRepository(Repository)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Repository()
	 * @see com.github.icelyframework.service.Repository#getAggregateRoot
	 * @model opposite="aggregateRoot" containment="true"
	 * @generated
	 */
	Repository getRepository();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getRepository <em>Repository</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Repository</em>' containment reference.
	 * @see #getRepository()
	 * @generated
	 */
	void setRepository(Repository value);

	/**
	 * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
	 * The list contents are of type {@link com.github.icelyframework.service.DomainObjectOperation}.
	 * It is bidirectional and its opposite is '{@link com.github.icelyframework.service.DomainObjectOperation#getDomainobject <em>Domainobject</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Operations</em>' containment reference list.
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Operations()
	 * @see com.github.icelyframework.service.DomainObjectOperation#getDomainobject
	 * @model opposite="domainobject" containment="true"
	 * @generated
	 */
	EList<DomainObjectOperation> getOperations();

	/**
	 * Returns the value of the '<em><b>Aggregate</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link com.github.icelyframework.service.Aggregate#getDomainobjects <em>Domainobjects</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Aggregate</em>' container reference.
	 * @see #setAggregate(Aggregate)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Aggregate()
	 * @see com.github.icelyframework.service.Aggregate#getDomainobjects
	 * @model opposite="domainobjects" required="true" transient="false"
	 * @generated
	 */
	Aggregate getAggregate();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getAggregate <em>Aggregate</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Aggregate</em>' container reference.
	 * @see #getAggregate()
	 * @generated
	 */
	void setAggregate(Aggregate value);

	/**
	 * Returns the value of the '<em><b>Package</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Package</em>' attribute.
	 * @see #setPackage(String)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Package()
	 * @model unique="false"
	 * @generated
	 */
	String getPackage();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getPackage <em>Package</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Package</em>' attribute.
	 * @see #getPackage()
	 * @generated
	 */
	void setPackage(String value);

	/**
	 * Returns the value of the '<em><b>Gap Class</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Gap Class</em>' attribute.
	 * @see #setGapClass(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_GapClass()
	 * @model unique="false"
	 * @generated
	 */
	boolean isGapClass();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isGapClass <em>Gap Class</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Gap Class</em>' attribute.
	 * @see #isGapClass()
	 * @generated
	 */
	void setGapClass(boolean value);

	/**
	 * Returns the value of the '<em><b>Cache</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Cache</em>' attribute.
	 * @see #setCache(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Cache()
	 * @model unique="false"
	 * @generated
	 */
	boolean isCache();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isCache <em>Cache</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cache</em>' attribute.
	 * @see #isCache()
	 * @generated
	 */
	void setCache(boolean value);

	/**
	 * Returns the value of the '<em><b>Optimistic Locking</b></em>' attribute.
	 * The default value is <code>"true"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Optimistic Locking</em>' attribute.
	 * @see #setOptimisticLocking(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_OptimisticLocking()
	 * @model default="true" unique="false"
	 * @generated
	 */
	boolean isOptimisticLocking();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isOptimisticLocking <em>Optimistic Locking</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Optimistic Locking</em>' attribute.
	 * @see #isOptimisticLocking()
	 * @generated
	 */
	void setOptimisticLocking(boolean value);

	/**
	 * Returns the value of the '<em><b>Database Table</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Database Table</em>' attribute.
	 * @see #setDatabaseTable(String)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_DatabaseTable()
	 * @model unique="false"
	 * @generated
	 */
	String getDatabaseTable();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getDatabaseTable <em>Database Table</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Database Table</em>' attribute.
	 * @see #getDatabaseTable()
	 * @generated
	 */
	void setDatabaseTable(String value);

	/**
	 * Returns the value of the '<em><b>Validate</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Validate</em>' attribute.
	 * @see #setValidate(String)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Validate()
	 * @model unique="false"
	 * @generated
	 */
	String getValidate();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getValidate <em>Validate</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Validate</em>' attribute.
	 * @see #getValidate()
	 * @generated
	 */
	void setValidate(String value);

	/**
	 * Returns the value of the '<em><b>Discriminator Column Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Discriminator Column Value</em>' attribute.
	 * @see #setDiscriminatorColumnValue(String)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_DiscriminatorColumnValue()
	 * @model unique="false"
	 * @generated
	 */
	String getDiscriminatorColumnValue();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#getDiscriminatorColumnValue <em>Discriminator Column Value</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Discriminator Column Value</em>' attribute.
	 * @see #getDiscriminatorColumnValue()
	 * @generated
	 */
	void setDiscriminatorColumnValue(String value);

	/**
	 * Returns the value of the '<em><b>Scaffold</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Scaffold</em>' attribute.
	 * @see #setScaffold(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_Scaffold()
	 * @model
	 * @generated
	 */
	boolean isScaffold();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isScaffold <em>Scaffold</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Scaffold</em>' attribute.
	 * @see #isScaffold()
	 * @generated
	 */
	void setScaffold(boolean value);

	/**
	 * Returns the value of the '<em><b>Generated By JHipster</b></em>' attribute.
	 * The default value is <code>"False"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By JHipster</em>' attribute.
	 * @see #setGeneratedByJHipster(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_GeneratedByJHipster()
	 * @model default="False"
	 * @generated
	 */
	boolean isGeneratedByJHipster();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isGeneratedByJHipster <em>Generated By JHipster</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By JHipster</em>' attribute.
	 * @see #isGeneratedByJHipster()
	 * @generated
	 */
	void setGeneratedByJHipster(boolean value);

	/**
	 * Returns the value of the '<em><b>Generated By Sculptor</b></em>' attribute.
	 * The default value is <code>"True"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By Sculptor</em>' attribute.
	 * @see #setGeneratedBySculptor(boolean)
	 * @see com.github.icelyframework.service.ServicePackage#getDomainObject_GeneratedBySculptor()
	 * @model default="True"
	 * @generated
	 */
	boolean isGeneratedBySculptor();

	/**
	 * Sets the value of the '{@link com.github.icelyframework.service.DomainObject#isGeneratedBySculptor <em>Generated By Sculptor</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By Sculptor</em>' attribute.
	 * @see #isGeneratedBySculptor()
	 * @generated
	 */
	void setGeneratedBySculptor(boolean value);

} // DomainObject
