<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment" nsURI="http://github.com/icelyframework/deployment"
    nsPrefix="icely">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseType">
    <eLiterals name="SQL"/>
    <eLiterals name="MONGODB" value="1"/>
    <eLiterals name="CASSANDRA" value="2"/>
    <eLiterals name="COUCHBASE" value="3"/>
    <eLiterals name="NO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationDeployment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoryPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbIP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbUsername" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbType" eType="#//DatabaseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1"
        eType="#//Application" eOpposite="#//Application/deployment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectDeployment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dockerRepositoryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoryPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceDiscoveryType" eType="#//ServiceDiscoveryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayType" eType="#//GatewayType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentType" eType="#//DeploymentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appsFolders" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitoring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kubernetesServiceType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/deployment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceDiscoveryType">
    <eLiterals name="EUREKA"/>
    <eLiterals name="CONSUL" value="1"/>
    <eLiterals name="NO" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentType">
    <eLiterals name="DOCKER_COMPOSE"/>
    <eLiterals name="KUBERNETES" value="1"/>
    <eLiterals name="OPENSHIFT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayType">
    <eLiterals name="ZUUL"/>
    <eLiterals name="TRAEFIK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true" eOpposite="#//Application/project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" upperBound="-1"
        eType="#//ProjectDeployment" containment="true" eOpposite="#//ProjectDeployment/project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/applications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationType" eType="#//ApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" upperBound="-1"
        eType="#//ApplicationDeployment" containment="true" eOpposite="#//ApplicationDeployment/application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApplicationType">
    <eLiterals name="JHIPSTER_MICROSERVICE"/>
    <eLiterals name="JHIPSTER_GATEWAY" value="1"/>
    <eLiterals name="JHIPSTER_MONOLITH" value="2"/>
    <eLiterals name="JHIPSTER_UAA" value="3"/>
    <eLiterals name="SCULPTOR_MICROSERVICE" value="4"/>
    <eLiterals name="SCULPTOR_MONOLITH" value="5"/>
  </eClassifiers>
</ecore:EPackage>
