<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jdl" nsURI="http://github.com/icelyframework/jdl" nsPrefix="icely">
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//Config" containment="true" eOpposite="#//Config/application"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//DTO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginates" upperBound="-1"
        eType="#//Paginate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="search" upperBound="-1"
        eType="#//Search"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationType" eType="#//ApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servicePort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseType" eType="#//DatabaseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildTool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtoSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableHibernateCache" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entitySuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jhiPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nativeLanguage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipClient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipServer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipUserManagement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uaaBaseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testFrameworks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationType" eType="#//AuthenticationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheProvider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1"
        eType="#//Application" eOpposite="#//Application/config"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApplicationType">
    <eLiterals name="MICROSERVICE"/>
    <eLiterals name="GATEWAY" value="1"/>
    <eLiterals name="MONOLITH" value="2"/>
    <eLiterals name="UAA" value="3" literal="UAA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseType">
    <eLiterals name="SQL"/>
    <eLiterals name="MONGODB" value="1"/>
    <eLiterals name="CASSANDRA" value="2"/>
    <eLiterals name="COUCHBASE" value="3"/>
    <eLiterals name="NO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromColumn" lowerBound="1"
        eType="#//RelationshipColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="ONE_TO_MANY" literal="ONE_TO_MANY"/>
    <eLiterals name="MANY_TO_ONE" value="1" literal="MANY_TO_ONE"/>
    <eLiterals name="ONE_TO_ONE" value="2" literal="ONE_TO_ONE"/>
    <eLiterals name="MANY_TO_MANY" value="3" literal="MANY_TO_MANY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
    <eLiterals name="UNIDIRECTIONAL" literal="UNIDIRECTIONAL"/>
    <eLiterals name="BIDIRECTIONAL" value="1" literal="BIDIRECTIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRequired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JDL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//Enum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginate" upperBound="-1"
        eType="#//Paginate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dto" upperBound="-1" eType="#//DTO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="search" upperBound="-1"
        eType="#//Search" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployments" eType="#//Deployment"
        eOpposite="#//Deployment/application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentType" eType="#//DeploymentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoryPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dockerRepositoryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appsFolders" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceDiscoveryType" eType="#//ServiceDiscoveryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitoring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayType" eType="#//GatewayType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kubernetesServiceType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1"
        eType="#//JDL" eOpposite="#//JDL/deployments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentType">
    <eLiterals name="DOCKER_COMPOSE"/>
    <eLiterals name="KUBERNETES" value="1"/>
    <eLiterals name="OPENSHIFT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnidirectionalRelationship" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toEntity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidirectionalRelationship" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toColumn" lowerBound="1"
        eType="#//RelationshipColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paginate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PaginationValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//DTOValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ServiceValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuildToolType">
    <eLiterals name="MAVEN"/>
    <eLiterals name="GRADLE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CacheProviderType">
    <eLiterals name="EHCACHE"/>
    <eLiterals name="HAZELCAST" value="1"/>
    <eLiterals name="CAFFEINE" value="2"/>
    <eLiterals name="MEMCACHED" value="3"/>
    <eLiterals name="REDIS" value="4"/>
    <eLiterals name="NO" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClientFramework">
    <eLiterals name="ANGULARX"/>
    <eLiterals name="NO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SearchEngine">
    <eLiterals name="ELASTICSEARCH"/>
    <eLiterals name="NO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageBroker">
    <eLiterals name="KAFKA"/>
    <eLiterals name="NO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Search">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//SearchEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthenticationType">
    <eLiterals name="JWT"/>
    <eLiterals name="UAA" value="1"/>
    <eLiterals name="SESSION" value="2"/>
    <eLiterals name="OAUTH2" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceDiscoveryType">
    <eLiterals name="EUREKA"/>
    <eLiterals name="CONSUL" value="1"/>
    <eLiterals name="NO" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayType">
    <eLiterals name="ZUUL"/>
    <eLiterals name="TRAEFIK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceValue">
    <eLiterals name="SERVICE_CLASS" literal="SERVICE_CLASS"/>
    <eLiterals name="NO" value="1"/>
    <eLiterals name="SERVICE_IMPL" value="2" literal="SERVICE_IMPL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DTOValue">
    <eLiterals name="MAPSTRUCT" literal="MAPSTRUCT"/>
    <eLiterals name="NO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaginationValue">
    <eLiterals name="PAGINATION" literal="PAGINATION"/>
    <eLiterals name="NO" value="1"/>
    <eLiterals name="INFINITE_SCROLL" value="2" literal="INFINITE_SCROLL"/>
  </eClassifiers>
</ecore:EPackage>
