/**
 */
package com.github.icelyframework.service.impl;

import com.github.icelyframework.service.DomainObject;
import com.github.icelyframework.service.Relation;
import com.github.icelyframework.service.RelationType;
import com.github.icelyframework.service.ServicePackage;
import com.github.icelyframework.service.TypeDefinition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.EObjectImpl;

import org.eclipse.emf.ecore.util.EcoreUtil;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getSource <em>Source</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getCascade <em>Cascade</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getOrderBy <em>Order By</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isRequired <em>Required</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isNullable <em>Nullable</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getOpposite <em>Opposite</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getRelationType <em>Relation Type</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isChangeable <em>Changeable</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isCache <em>Cache</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getDatabaseJoinColumn <em>Database Join Column</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isInverse <em>Inverse</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getValidate <em>Validate</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isTransient <em>Transient</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getDatabaseJoinTable <em>Database Join Table</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#getType <em>Type</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isGeneratedBySculptor <em>Generated By Sculptor</em>}</li>
 *   <li>{@link com.github.icelyframework.service.impl.RelationImpl#isGeneratedByJHipster <em>Generated By JHipster</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationImpl extends EObjectImpl implements Relation {
	/**
	 * The cached value of the '{@link #getTarget() <em>Target</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTarget()
	 * @generated
	 * @ordered
	 */
	protected DomainObject target;

	/**
	 * The default value of the '{@link #getCascade() <em>Cascade</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCascade()
	 * @generated
	 * @ordered
	 */
	protected static final String CASCADE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getCascade() <em>Cascade</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCascade()
	 * @generated
	 * @ordered
	 */
	protected String cascade = CASCADE_EDEFAULT;

	/**
	 * The default value of the '{@link #getOrderBy() <em>Order By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrderBy()
	 * @generated
	 * @ordered
	 */
	protected static final String ORDER_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getOrderBy() <em>Order By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrderBy()
	 * @generated
	 * @ordered
	 */
	protected String orderBy = ORDER_BY_EDEFAULT;

	/**
	 * The default value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVisibility()
	 * @generated
	 * @ordered
	 */
	protected static final String VISIBILITY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVisibility()
	 * @generated
	 * @ordered
	 */
	protected String visibility = VISIBILITY_EDEFAULT;

	/**
	 * The default value of the '{@link #isRequired() <em>Required</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isRequired()
	 * @generated
	 * @ordered
	 */
	protected static final boolean REQUIRED_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isRequired() <em>Required</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isRequired()
	 * @generated
	 * @ordered
	 */
	protected boolean required = REQUIRED_EDEFAULT;

	/**
	 * The default value of the '{@link #isNullable() <em>Nullable</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isNullable()
	 * @generated
	 * @ordered
	 */
	protected static final boolean NULLABLE_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isNullable() <em>Nullable</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isNullable()
	 * @generated
	 * @ordered
	 */
	protected boolean nullable = NULLABLE_EDEFAULT;

	/**
	 * The cached value of the '{@link #getOpposite() <em>Opposite</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOpposite()
	 * @generated
	 * @ordered
	 */
	protected Relation opposite;

	/**
	 * The default value of the '{@link #getRelationType() <em>Relation Type</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRelationType()
	 * @generated
	 * @ordered
	 */
	protected static final RelationType RELATION_TYPE_EDEFAULT = RelationType.COMPOSITION;

	/**
	 * The cached value of the '{@link #getRelationType() <em>Relation Type</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRelationType()
	 * @generated
	 * @ordered
	 */
	protected RelationType relationType = RELATION_TYPE_EDEFAULT;

	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The default value of the '{@link #isChangeable() <em>Changeable</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isChangeable()
	 * @generated
	 * @ordered
	 */
	protected static final boolean CHANGEABLE_EDEFAULT = true;

	/**
	 * The cached value of the '{@link #isChangeable() <em>Changeable</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isChangeable()
	 * @generated
	 * @ordered
	 */
	protected boolean changeable = CHANGEABLE_EDEFAULT;

	/**
	 * The default value of the '{@link #isCache() <em>Cache</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isCache()
	 * @generated
	 * @ordered
	 */
	protected static final boolean CACHE_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isCache() <em>Cache</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isCache()
	 * @generated
	 * @ordered
	 */
	protected boolean cache = CACHE_EDEFAULT;

	/**
	 * The default value of the '{@link #getDatabaseJoinColumn() <em>Database Join Column</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDatabaseJoinColumn()
	 * @generated
	 * @ordered
	 */
	protected static final String DATABASE_JOIN_COLUMN_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDatabaseJoinColumn() <em>Database Join Column</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDatabaseJoinColumn()
	 * @generated
	 * @ordered
	 */
	protected String databaseJoinColumn = DATABASE_JOIN_COLUMN_EDEFAULT;

	/**
	 * The default value of the '{@link #isInverse() <em>Inverse</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isInverse()
	 * @generated
	 * @ordered
	 */
	protected static final boolean INVERSE_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isInverse() <em>Inverse</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isInverse()
	 * @generated
	 * @ordered
	 */
	protected boolean inverse = INVERSE_EDEFAULT;

	/**
	 * The default value of the '{@link #getValidate() <em>Validate</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getValidate()
	 * @generated
	 * @ordered
	 */
	protected static final String VALIDATE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getValidate() <em>Validate</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getValidate()
	 * @generated
	 * @ordered
	 */
	protected String validate = VALIDATE_EDEFAULT;

	/**
	 * The default value of the '{@link #isTransient() <em>Transient</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isTransient()
	 * @generated
	 * @ordered
	 */
	protected static final boolean TRANSIENT_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isTransient() <em>Transient</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isTransient()
	 * @generated
	 * @ordered
	 */
	protected boolean transient_ = TRANSIENT_EDEFAULT;

	/**
	 * The default value of the '{@link #getDatabaseJoinTable() <em>Database Join Table</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDatabaseJoinTable()
	 * @generated
	 * @ordered
	 */
	protected static final String DATABASE_JOIN_TABLE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDatabaseJoinTable() <em>Database Join Table</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDatabaseJoinTable()
	 * @generated
	 * @ordered
	 */
	protected String databaseJoinTable = DATABASE_JOIN_TABLE_EDEFAULT;

	/**
	 * The cached value of the '{@link #getType() <em>Type</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getType()
	 * @generated
	 * @ordered
	 */
	protected TypeDefinition type;

	/**
	 * The default value of the '{@link #isGeneratedBySculptor() <em>Generated By Sculptor</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isGeneratedBySculptor()
	 * @generated
	 * @ordered
	 */
	protected static final boolean GENERATED_BY_SCULPTOR_EDEFAULT = true;

	/**
	 * The cached value of the '{@link #isGeneratedBySculptor() <em>Generated By Sculptor</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isGeneratedBySculptor()
	 * @generated
	 * @ordered
	 */
	protected boolean generatedBySculptor = GENERATED_BY_SCULPTOR_EDEFAULT;

	/**
	 * The default value of the '{@link #isGeneratedByJHipster() <em>Generated By JHipster</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isGeneratedByJHipster()
	 * @generated
	 * @ordered
	 */
	protected static final boolean GENERATED_BY_JHIPSTER_EDEFAULT = false;

	/**
	 * The cached value of the '{@link #isGeneratedByJHipster() <em>Generated By JHipster</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isGeneratedByJHipster()
	 * @generated
	 * @ordered
	 */
	protected boolean generatedByJHipster = GENERATED_BY_JHIPSTER_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return ServicePackage.Literals.RELATION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public DomainObject getTarget() {
		if (target != null && target.eIsProxy()) {
			InternalEObject oldTarget = (InternalEObject)target;
			target = (DomainObject)eResolveProxy(oldTarget);
			if (target != oldTarget) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, ServicePackage.RELATION__TARGET, oldTarget, target));
			}
		}
		return target;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DomainObject basicGetTarget() {
		return target;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setTarget(DomainObject newTarget) {
		DomainObject oldTarget = target;
		target = newTarget;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__TARGET, oldTarget, target));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public DomainObject getSource() {
		if (eContainerFeatureID() != ServicePackage.RELATION__SOURCE) return null;
		return (DomainObject)eInternalContainer();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetSource(DomainObject newSource, NotificationChain msgs) {
		msgs = eBasicSetContainer((InternalEObject)newSource, ServicePackage.RELATION__SOURCE, msgs);
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setSource(DomainObject newSource) {
		if (newSource != eInternalContainer() || (eContainerFeatureID() != ServicePackage.RELATION__SOURCE && newSource != null)) {
			if (EcoreUtil.isAncestor(this, newSource))
				throw new IllegalArgumentException("Recursive containment not allowed for " + toString());
			NotificationChain msgs = null;
			if (eInternalContainer() != null)
				msgs = eBasicRemoveFromContainer(msgs);
			if (newSource != null)
				msgs = ((InternalEObject)newSource).eInverseAdd(this, ServicePackage.DOMAIN_OBJECT__RELATIONS, DomainObject.class, msgs);
			msgs = basicSetSource(newSource, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__SOURCE, newSource, newSource));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCascade() {
		return cascade;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCascade(String newCascade) {
		String oldCascade = cascade;
		cascade = newCascade;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__CASCADE, oldCascade, cascade));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getOrderBy() {
		return orderBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOrderBy(String newOrderBy) {
		String oldOrderBy = orderBy;
		orderBy = newOrderBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__ORDER_BY, oldOrderBy, orderBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getVisibility() {
		return visibility;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setVisibility(String newVisibility) {
		String oldVisibility = visibility;
		visibility = newVisibility;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__VISIBILITY, oldVisibility, visibility));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isRequired() {
		return required;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setRequired(boolean newRequired) {
		boolean oldRequired = required;
		required = newRequired;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__REQUIRED, oldRequired, required));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isNullable() {
		return nullable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setNullable(boolean newNullable) {
		boolean oldNullable = nullable;
		nullable = newNullable;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__NULLABLE, oldNullable, nullable));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Relation getOpposite() {
		if (opposite != null && opposite.eIsProxy()) {
			InternalEObject oldOpposite = (InternalEObject)opposite;
			opposite = (Relation)eResolveProxy(oldOpposite);
			if (opposite != oldOpposite) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, ServicePackage.RELATION__OPPOSITE, oldOpposite, opposite));
			}
		}
		return opposite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Relation basicGetOpposite() {
		return opposite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOpposite(Relation newOpposite) {
		Relation oldOpposite = opposite;
		opposite = newOpposite;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__OPPOSITE, oldOpposite, opposite));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public RelationType getRelationType() {
		return relationType;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setRelationType(RelationType newRelationType) {
		RelationType oldRelationType = relationType;
		relationType = newRelationType == null ? RELATION_TYPE_EDEFAULT : newRelationType;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__RELATION_TYPE, oldRelationType, relationType));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isChangeable() {
		return changeable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setChangeable(boolean newChangeable) {
		boolean oldChangeable = changeable;
		changeable = newChangeable;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__CHANGEABLE, oldChangeable, changeable));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isCache() {
		return cache;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCache(boolean newCache) {
		boolean oldCache = cache;
		cache = newCache;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__CACHE, oldCache, cache));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDatabaseJoinColumn() {
		return databaseJoinColumn;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDatabaseJoinColumn(String newDatabaseJoinColumn) {
		String oldDatabaseJoinColumn = databaseJoinColumn;
		databaseJoinColumn = newDatabaseJoinColumn;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__DATABASE_JOIN_COLUMN, oldDatabaseJoinColumn, databaseJoinColumn));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isInverse() {
		return inverse;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setInverse(boolean newInverse) {
		boolean oldInverse = inverse;
		inverse = newInverse;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__INVERSE, oldInverse, inverse));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getValidate() {
		return validate;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setValidate(String newValidate) {
		String oldValidate = validate;
		validate = newValidate;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__VALIDATE, oldValidate, validate));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isTransient() {
		return transient_;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setTransient(boolean newTransient) {
		boolean oldTransient = transient_;
		transient_ = newTransient;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__TRANSIENT, oldTransient, transient_));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDatabaseJoinTable() {
		return databaseJoinTable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDatabaseJoinTable(String newDatabaseJoinTable) {
		String oldDatabaseJoinTable = databaseJoinTable;
		databaseJoinTable = newDatabaseJoinTable;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__DATABASE_JOIN_TABLE, oldDatabaseJoinTable, databaseJoinTable));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public TypeDefinition getType() {
		if (type != null && type.eIsProxy()) {
			InternalEObject oldType = (InternalEObject)type;
			type = (TypeDefinition)eResolveProxy(oldType);
			if (type != oldType) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, ServicePackage.RELATION__TYPE, oldType, type));
			}
		}
		return type;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TypeDefinition basicGetType() {
		return type;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setType(TypeDefinition newType) {
		TypeDefinition oldType = type;
		type = newType;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__TYPE, oldType, type));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isGeneratedBySculptor() {
		return generatedBySculptor;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBySculptor(boolean newGeneratedBySculptor) {
		boolean oldGeneratedBySculptor = generatedBySculptor;
		generatedBySculptor = newGeneratedBySculptor;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__GENERATED_BY_SCULPTOR, oldGeneratedBySculptor, generatedBySculptor));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isGeneratedByJHipster() {
		return generatedByJHipster;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedByJHipster(boolean newGeneratedByJHipster) {
		boolean oldGeneratedByJHipster = generatedByJHipster;
		generatedByJHipster = newGeneratedByJHipster;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ServicePackage.RELATION__GENERATED_BY_JHIPSTER, oldGeneratedByJHipster, generatedByJHipster));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ServicePackage.RELATION__SOURCE:
				if (eInternalContainer() != null)
					msgs = eBasicRemoveFromContainer(msgs);
				return basicSetSource((DomainObject)otherEnd, msgs);
		}
		return super.eInverseAdd(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ServicePackage.RELATION__SOURCE:
				return basicSetSource(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eBasicRemoveFromContainerFeature(NotificationChain msgs) {
		switch (eContainerFeatureID()) {
			case ServicePackage.RELATION__SOURCE:
				return eInternalContainer().eInverseRemove(this, ServicePackage.DOMAIN_OBJECT__RELATIONS, DomainObject.class, msgs);
		}
		return super.eBasicRemoveFromContainerFeature(msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case ServicePackage.RELATION__TARGET:
				if (resolve) return getTarget();
				return basicGetTarget();
			case ServicePackage.RELATION__SOURCE:
				return getSource();
			case ServicePackage.RELATION__CASCADE:
				return getCascade();
			case ServicePackage.RELATION__ORDER_BY:
				return getOrderBy();
			case ServicePackage.RELATION__VISIBILITY:
				return getVisibility();
			case ServicePackage.RELATION__REQUIRED:
				return isRequired();
			case ServicePackage.RELATION__NULLABLE:
				return isNullable();
			case ServicePackage.RELATION__OPPOSITE:
				if (resolve) return getOpposite();
				return basicGetOpposite();
			case ServicePackage.RELATION__RELATION_TYPE:
				return getRelationType();
			case ServicePackage.RELATION__NAME:
				return getName();
			case ServicePackage.RELATION__CHANGEABLE:
				return isChangeable();
			case ServicePackage.RELATION__CACHE:
				return isCache();
			case ServicePackage.RELATION__DATABASE_JOIN_COLUMN:
				return getDatabaseJoinColumn();
			case ServicePackage.RELATION__INVERSE:
				return isInverse();
			case ServicePackage.RELATION__VALIDATE:
				return getValidate();
			case ServicePackage.RELATION__TRANSIENT:
				return isTransient();
			case ServicePackage.RELATION__DATABASE_JOIN_TABLE:
				return getDatabaseJoinTable();
			case ServicePackage.RELATION__TYPE:
				if (resolve) return getType();
				return basicGetType();
			case ServicePackage.RELATION__GENERATED_BY_SCULPTOR:
				return isGeneratedBySculptor();
			case ServicePackage.RELATION__GENERATED_BY_JHIPSTER:
				return isGeneratedByJHipster();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case ServicePackage.RELATION__TARGET:
				setTarget((DomainObject)newValue);
				return;
			case ServicePackage.RELATION__SOURCE:
				setSource((DomainObject)newValue);
				return;
			case ServicePackage.RELATION__CASCADE:
				setCascade((String)newValue);
				return;
			case ServicePackage.RELATION__ORDER_BY:
				setOrderBy((String)newValue);
				return;
			case ServicePackage.RELATION__VISIBILITY:
				setVisibility((String)newValue);
				return;
			case ServicePackage.RELATION__REQUIRED:
				setRequired((Boolean)newValue);
				return;
			case ServicePackage.RELATION__NULLABLE:
				setNullable((Boolean)newValue);
				return;
			case ServicePackage.RELATION__OPPOSITE:
				setOpposite((Relation)newValue);
				return;
			case ServicePackage.RELATION__RELATION_TYPE:
				setRelationType((RelationType)newValue);
				return;
			case ServicePackage.RELATION__NAME:
				setName((String)newValue);
				return;
			case ServicePackage.RELATION__CHANGEABLE:
				setChangeable((Boolean)newValue);
				return;
			case ServicePackage.RELATION__CACHE:
				setCache((Boolean)newValue);
				return;
			case ServicePackage.RELATION__DATABASE_JOIN_COLUMN:
				setDatabaseJoinColumn((String)newValue);
				return;
			case ServicePackage.RELATION__INVERSE:
				setInverse((Boolean)newValue);
				return;
			case ServicePackage.RELATION__VALIDATE:
				setValidate((String)newValue);
				return;
			case ServicePackage.RELATION__TRANSIENT:
				setTransient((Boolean)newValue);
				return;
			case ServicePackage.RELATION__DATABASE_JOIN_TABLE:
				setDatabaseJoinTable((String)newValue);
				return;
			case ServicePackage.RELATION__TYPE:
				setType((TypeDefinition)newValue);
				return;
			case ServicePackage.RELATION__GENERATED_BY_SCULPTOR:
				setGeneratedBySculptor((Boolean)newValue);
				return;
			case ServicePackage.RELATION__GENERATED_BY_JHIPSTER:
				setGeneratedByJHipster((Boolean)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case ServicePackage.RELATION__TARGET:
				setTarget((DomainObject)null);
				return;
			case ServicePackage.RELATION__SOURCE:
				setSource((DomainObject)null);
				return;
			case ServicePackage.RELATION__CASCADE:
				setCascade(CASCADE_EDEFAULT);
				return;
			case ServicePackage.RELATION__ORDER_BY:
				setOrderBy(ORDER_BY_EDEFAULT);
				return;
			case ServicePackage.RELATION__VISIBILITY:
				setVisibility(VISIBILITY_EDEFAULT);
				return;
			case ServicePackage.RELATION__REQUIRED:
				setRequired(REQUIRED_EDEFAULT);
				return;
			case ServicePackage.RELATION__NULLABLE:
				setNullable(NULLABLE_EDEFAULT);
				return;
			case ServicePackage.RELATION__OPPOSITE:
				setOpposite((Relation)null);
				return;
			case ServicePackage.RELATION__RELATION_TYPE:
				setRelationType(RELATION_TYPE_EDEFAULT);
				return;
			case ServicePackage.RELATION__NAME:
				setName(NAME_EDEFAULT);
				return;
			case ServicePackage.RELATION__CHANGEABLE:
				setChangeable(CHANGEABLE_EDEFAULT);
				return;
			case ServicePackage.RELATION__CACHE:
				setCache(CACHE_EDEFAULT);
				return;
			case ServicePackage.RELATION__DATABASE_JOIN_COLUMN:
				setDatabaseJoinColumn(DATABASE_JOIN_COLUMN_EDEFAULT);
				return;
			case ServicePackage.RELATION__INVERSE:
				setInverse(INVERSE_EDEFAULT);
				return;
			case ServicePackage.RELATION__VALIDATE:
				setValidate(VALIDATE_EDEFAULT);
				return;
			case ServicePackage.RELATION__TRANSIENT:
				setTransient(TRANSIENT_EDEFAULT);
				return;
			case ServicePackage.RELATION__DATABASE_JOIN_TABLE:
				setDatabaseJoinTable(DATABASE_JOIN_TABLE_EDEFAULT);
				return;
			case ServicePackage.RELATION__TYPE:
				setType((TypeDefinition)null);
				return;
			case ServicePackage.RELATION__GENERATED_BY_SCULPTOR:
				setGeneratedBySculptor(GENERATED_BY_SCULPTOR_EDEFAULT);
				return;
			case ServicePackage.RELATION__GENERATED_BY_JHIPSTER:
				setGeneratedByJHipster(GENERATED_BY_JHIPSTER_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case ServicePackage.RELATION__TARGET:
				return target != null;
			case ServicePackage.RELATION__SOURCE:
				return getSource() != null;
			case ServicePackage.RELATION__CASCADE:
				return CASCADE_EDEFAULT == null ? cascade != null : !CASCADE_EDEFAULT.equals(cascade);
			case ServicePackage.RELATION__ORDER_BY:
				return ORDER_BY_EDEFAULT == null ? orderBy != null : !ORDER_BY_EDEFAULT.equals(orderBy);
			case ServicePackage.RELATION__VISIBILITY:
				return VISIBILITY_EDEFAULT == null ? visibility != null : !VISIBILITY_EDEFAULT.equals(visibility);
			case ServicePackage.RELATION__REQUIRED:
				return required != REQUIRED_EDEFAULT;
			case ServicePackage.RELATION__NULLABLE:
				return nullable != NULLABLE_EDEFAULT;
			case ServicePackage.RELATION__OPPOSITE:
				return opposite != null;
			case ServicePackage.RELATION__RELATION_TYPE:
				return relationType != RELATION_TYPE_EDEFAULT;
			case ServicePackage.RELATION__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case ServicePackage.RELATION__CHANGEABLE:
				return changeable != CHANGEABLE_EDEFAULT;
			case ServicePackage.RELATION__CACHE:
				return cache != CACHE_EDEFAULT;
			case ServicePackage.RELATION__DATABASE_JOIN_COLUMN:
				return DATABASE_JOIN_COLUMN_EDEFAULT == null ? databaseJoinColumn != null : !DATABASE_JOIN_COLUMN_EDEFAULT.equals(databaseJoinColumn);
			case ServicePackage.RELATION__INVERSE:
				return inverse != INVERSE_EDEFAULT;
			case ServicePackage.RELATION__VALIDATE:
				return VALIDATE_EDEFAULT == null ? validate != null : !VALIDATE_EDEFAULT.equals(validate);
			case ServicePackage.RELATION__TRANSIENT:
				return transient_ != TRANSIENT_EDEFAULT;
			case ServicePackage.RELATION__DATABASE_JOIN_TABLE:
				return DATABASE_JOIN_TABLE_EDEFAULT == null ? databaseJoinTable != null : !DATABASE_JOIN_TABLE_EDEFAULT.equals(databaseJoinTable);
			case ServicePackage.RELATION__TYPE:
				return type != null;
			case ServicePackage.RELATION__GENERATED_BY_SCULPTOR:
				return generatedBySculptor != GENERATED_BY_SCULPTOR_EDEFAULT;
			case ServicePackage.RELATION__GENERATED_BY_JHIPSTER:
				return generatedByJHipster != GENERATED_BY_JHIPSTER_EDEFAULT;
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (cascade: ");
		result.append(cascade);
		result.append(", orderBy: ");
		result.append(orderBy);
		result.append(", visibility: ");
		result.append(visibility);
		result.append(", required: ");
		result.append(required);
		result.append(", nullable: ");
		result.append(nullable);
		result.append(", relationType: ");
		result.append(relationType);
		result.append(", name: ");
		result.append(name);
		result.append(", changeable: ");
		result.append(changeable);
		result.append(", cache: ");
		result.append(cache);
		result.append(", databaseJoinColumn: ");
		result.append(databaseJoinColumn);
		result.append(", inverse: ");
		result.append(inverse);
		result.append(", validate: ");
		result.append(validate);
		result.append(", transient: ");
		result.append(transient_);
		result.append(", databaseJoinTable: ");
		result.append(databaseJoinTable);
		result.append(", generatedBySculptor: ");
		result.append(generatedBySculptor);
		result.append(", generatedByJHipster: ");
		result.append(generatedByJHipster);
		result.append(')');
		return result.toString();
	}

} //RelationImpl
