<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="http://github.com/icelyframework/service" nsPrefix="icely">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="ONE_TO_MANY" literal="ONE_TO_MANY"/>
    <eLiterals name="MANY_TO_ONE" value="1" literal="MANY_TO_ONE"/>
    <eLiterals name="ONE_TO_ONE" value="2" literal="ONE_TO_ONE"/>
    <eLiterals name="MANY_TO_MANY" value="3" literal="MANY_TO_MANY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true" eOpposite="#//Application/project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="architecture" lowerBound="1"
        eType="#//ArchitectureType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/applications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true" eOpposite="#//Module/application"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true" eOpposite="#//Role/application"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationType" eType="#//ApplicationType"
        defaultValueLiteral="SCULPTOR_MICROSERVICE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNamingProperty" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseColumn" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//DomainObject" eOpposite="#//DomainObject/relations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascade" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderBy" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationType" eType="#//RelationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cache" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseJoinColumn" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseJoinTable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedBySculptor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="True"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedByJHipster" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorColumnLength"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorType" unique="false"
        eType="#//DiscriminatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorColumnName"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//InheritanceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auditable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueObject" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainObject" lowerBound="1"
        upperBound="-1" eType="#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dto" lowerBound="1" eType="#//DTO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" eSuperTypes="#//ValueObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommandEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregateRoot" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true" eOpposite="#//Relation/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritance" eType="#//Inheritance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        containment="true" eOpposite="#//Repository/aggregateRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//DomainObjectOperation" containment="true" eOpposite="#//DomainObjectOperation/domainobject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" lowerBound="1"
        eType="#//Aggregate" eOpposite="#//Aggregate/domainobjects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gapClass" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cache" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimisticLocking" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseTable" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorColumnValue"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaffold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedByJHipster" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedBySculptor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="True"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainobjects" lowerBound="1"
        upperBound="-1" eType="#//DomainObject" containment="true" eOpposite="#//DomainObject/aggregate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/aggregates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateRoot" lowerBound="1"
        eType="#//DomainObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTO" eSuperTypes="#//ValueObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//ValueObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DefaultType">
    <eLiterals name="String"/>
    <eLiterals name="Integer" value="1"/>
    <eLiterals name="Float" value="2"/>
    <eLiterals name="Boolean" value="3"/>
    <eLiterals name="null" value="4"/>
    <eLiterals name="Date" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethod">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="GET"/>
    <eLiterals name="POST"/>
    <eLiterals name="PUT"/>
    <eLiterals name="DELETE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//RepositoryOperation" containment="true" resolveProxies="false" eOpposite="#//RepositoryOperation/repository"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryDependencies"
        upperBound="-1" eType="#//Repository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherDependencies" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribe" eType="#//Subscribe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateRoot" eType="#//DomainObject"
        eOpposite="#//DomainObject/repository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gapClass" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//Resource"
        eOpposite="#//Resource/operations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpMethod" unique="false"
        eType="#//HttpMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnString" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceParams" upperBound="-1"
        eType="#//ResourceParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDependencies" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//ResourceOperation" containment="true" resolveProxies="false" eOpposite="#//ResourceOperation/resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gapClass" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/resources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
        eType="#//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputrepresentation" eType="#//InputRepresentation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputrepresentation" eType="#//OutputRepresentation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//Service" eOpposite="#//Service/operations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDelegate" eType="#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="#//RepositoryOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegateToAccessObject"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessObjectName" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//Repository" eOpposite="#//Repository/operations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="select" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObjectOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainobject" eType="#//DomainObject"
        eOpposite="#//DomainObject/operations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryDependencies"
        upperBound="-1" eType="#//Repository"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDependencies" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="channel" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherDependencies" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribe" eType="#//Subscribe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageRoot" eType="#//DomainObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscribe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventBus" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//ServiceOperation" containment="true" resolveProxies="false" eOpposite="#//ServiceOperation/service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryDependencies"
        upperBound="-1" eType="#//Repository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherDependencies" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDependencies" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webService" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remoteInterface" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localInterface" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribe" eType="#//Subscribe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gapClass" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/services"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throws" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publish" eType="#//Publish"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publish">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventBus" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationType">
    <eLiterals name="COMPOSITION"/>
    <eLiterals name="ASSOCIATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InheritanceType">
    <eLiterals name="SINGLE_TABLE"/>
    <eLiterals name="JOINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiscriminatorType">
    <eLiterals name="STRING"/>
    <eLiterals name="CHAR"/>
    <eLiterals name="INTEGER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionType">
    <eLiterals name="SET"/>
    <eLiterals name="LIST" value="1"/>
    <eLiterals name="BAG" value="2"/>
    <eLiterals name="MAP" value="3"/>
    <eLiterals name="COLLECTION" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistenceUnit" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregates" upperBound="-1"
        eType="#//Aggregate" containment="true" eOpposite="#//Aggregate/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//Application"
        eOpposite="#//Application/modules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true" eOpposite="#//Service/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true" eOpposite="#//Resource/module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArchitectureType">
    <eLiterals name="SIMPLE"/>
    <eLiterals name="CQRS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasAnyAuthorities" eSuperTypes="#//Permission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasAuthority" eSuperTypes="#//Permission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Authenticated" eSuperTypes="#//Permission"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthenticationType">
    <eLiterals name="CENTERALIZED"/>
    <eLiterals name="DECENTERALIZED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" eSuperTypes="#//Permission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PermitAll" eSuperTypes="#//Permission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="withAllSubresources" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1"
        eType="#//Application" eOpposite="#//Application/roles"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryType" eType="#//QueryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryType">
    <eLiterals name="NONE"/>
    <eLiterals name="PAGE" value="1"/>
    <eLiterals name="SIZE" value="2"/>
    <eLiterals name="SORT" value="3"/>
    <eLiterals name="SEARCH" value="4"/>
    <eLiterals name="FILTER" value="5"/>
    <eLiterals name="SELECT" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApplicationType">
    <eLiterals name="JHIPSTER_MICROSERVICE"/>
    <eLiterals name="JHIPSTER_GATEWAY" value="1"/>
    <eLiterals name="JHIPSTER_MONOLITH" value="2"/>
    <eLiterals name="JHIPSTER_UAA" value="3"/>
    <eLiterals name="SCULPTOR_MICROSERVICE" value="4"/>
    <eLiterals name="SCULPTOR_MONOLITH" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputMediaType" unique="false"
        lowerBound="1" eType="#//MediaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputMediaType" unique="false"
        lowerBound="1" eType="#//MediaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MediaType">
    <eLiterals name="JSON"/>
    <eLiterals name="XML" value="1"/>
  </eClassifiers>
</ecore:EPackage>
